### ISSUE TITLE
Add system dependencies to docs

### ISSUE THREAD

**Issue by JavierBJ** [kuleshov/cornell-cs5785-2021-applied-ml#2]
Hello @kuleshov, thank you very much for your impressive work and your sharing efforts.

When I was following the instructions to compile the notes, slides and pdfs, I found out I had to install some system packages needed for `pandoc` to work. In Ubuntu, these are:

```bash
sudo apt-get install sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic pandoc
```

I suggest this could be added to the README so nobody gets stuck due to that. These TeX dependencies will likely be installed already in the computers of most researchers, but not in so many applied practitioners who will be interested in this applied course :smiley: .

Kind regards,
Javier

**Comment by kuleshov** [comment]
Thank you for the feedback @JavierBJ ! Any chance you could add these to the readme and file a PR? I'll be happy to merge it!

**Comment by miltondp** [comment]
@kuleshov thank you so much for this invaluable resource.

Related to this issue, I'm having this error when I run the pip command mentioned in the README file:

```bash
...

Collecting lxml==4.6.3 (from -r requirements.txt (line 28))
  Downloading lxml-4.6.3.tar.gz (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 27.7 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      /tmp/pip-install-a5vxxrco/lxml_31c4a92ae41648dcbf47c1679ed964fd/setup.py:64: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Building lxml version 4.6.3.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]

...
```

Which is fixed after installing those packages:

```bash
sudo apt install libxml2-dev libxslt1-dev
```

However, then I got issues when installing matplotlib:

```bash
...

Collecting matplotlib==3.2.1 (from -r requirements.txt (line 30))
  Downloading matplotlib-3.2.1.tar.gz (40.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 MB 30.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      /tmp/pip-install-vip9rjla/matplotlib_bd59ec560ca64e89a96ed6a9c622f3f5/setup.py:31: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************
      
      !!
        from setuptools.command.test import test as TestCommand
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-vip9rjla/matplotlib_bd59ec560ca64e89a96ed6a9c622f3f5/setup.py", line 50, in <module>
          __version__ = versioneer.get_version()
                        ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-vip9rjla/matplotlib_bd59ec560ca64e89a96ed6a9c622f3f5/versioneer.py", line 1410, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-vip9rjla/matplotlib_bd59ec560ca64e89a96ed6a9c622f3f5/versioneer.py", line 1344, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-vip9rjla/matplotlib_bd59ec560ca64e89a96ed6a9c622f3f5/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

...
```

Which [seems to be related](https://discuss.streamlit.io/t/error-installing-requirements-matplotlib/68952) to conflicting versions of Python and matplotlib.

I believe this could be solved by using conda and simplify the dependencies file. I'll comment back and open a PR if I succeed on this.
